# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'TestTaskWaadsu' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestTaskWaadsu

  target 'TestTaskWaadsuTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Quick'
    pod 'Nimble'
  end

  target 'TestTaskWaadsuUITests' do
    # Pods for testing
  end

end
